
CREATE TABLE IF NOT EXISTS $table (
  ID SERIAL PRIMARY KEY NOT NULL,
  Version VARCHAR(255) NOT NULL,
  Command VARCHAR(255) NOT NULL,
  Type VARCHAR(255) NOT NULL,
  Name VARCHAR(255) NOT NULL,
  Definition TEXT
);
